services:
  ghost:
    image: ghost:5-alpine
    restart: always
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      NODE_ENV: development
    volumes:
      - ./backend:/var/lib/ghost/content
    user: "1000:1000"
    depends_on:
      - db

  astro:
    build:
      context: .
      dockerfile: ./infra/dev/astro/Dockerfile
    volumes:
      - ./frontend:/usr/src/frontend
    restart: always
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: development
    user: "1000:1000"
    # デフォルトのlocalhostだとDockerがバインドしてくれなくてERR_EMPTY_RESPONSEになるので明示的に0.0.0.0を指定
    command: sh -c "pnpm install && pnpm dev --host 0.0.0.0"

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

volumes:
  db-store:

networks:
  default:
    name: nginx-proxy
    external: true
