services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 1110:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      url: http://localhost:1110
      NODE_ENV: development
    volumes:
      - ./backend:/var/lib/ghost/content

  astro:
    build:
      context: .
      dockerfile: ./infra/dev/astro/Dockerfile
    volumes:
      - ./frontend:/usr/src/frontend
    ports:
      - "1111:3000"
    restart: always
    environment:
      NODE_ENV: development

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

volumes:
  db-store:
