services:
  ghost:
    image: ghost:5-alpine
    restart: always
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      # 恐ろしく脆弱なDB設定だがコンテナの外に出していないやつなので、これでOKとする
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      NODE_ENV: production
      url: ${BACKEND_API_URL}
    volumes:
      - ./backend:/var/lib/ghost/content
    user: "1000:1000"
    depends_on:
      - db

  astro:
    image: ghcr.io/usuyuki/usuyuki_blog_v2_astro:latest
    # build:
    #   context: .
    #   dockerfile: ./infra/prod/astro/Dockerfile
    restart: always
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: production
      GHOST_CONTENT_KEY: ${GHOST_CONTENT_KEY}
      GHOST_API_URL: ${GHOST_API_URL}
    user: "1000:1000"
    depends_on:
      - ghost

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

volumes:
  db-store:

networks:
  default:
    name: nginx-proxy
    external: true
