name: 自動デプロイと初期構築

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/usuyuki_blog_v2_astro
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.USUYUKI_GITHUB_TOKEN }}
      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./infra/dev/astro/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/usuyuki_blog_v2_astro:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/usuyuki_blog_v2_astro:latest
          labels: latest

  deploy:
    name: Deploy to Server
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: cd ${{ secrets.BLOG_SERVER_PATH }} && docker compose up -d --build
